spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderflow
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
