spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderflow
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG